version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - postgres
      - redis
    ports:
      - '61234:61234'
    environment:
      - TEST_SERVER_PORT=61234
  postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: sectors
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 1s
      retries: 5
  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 1s
      retries: 5
