FROM node:21-slim as build

WORKDIR /app
COPY ui/ . \
     package.json \
     package-lock.json \
     tsconfig.json \
     tsconfig.node.json \
     vite.config.ts \
     vite-env.d.ts ./

RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
