
spring:
  session:
    store-type: redis
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://postgres:5432/sectors
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: none # Use 'update' for development
    show-sql: false
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        temp.use_jdbc_metadata_defaults: false
        id.new_generator_mappings: true
        cache.use_second_level_cache: false
        cache.use_query_cache: false
        generate_statistics: false

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} %X{transactionId}- %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} %X{transactionId}- %msg%n'

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m
  port: ${SERVER_PORT:8081}
