name: Build & Test

on:
  push:
  pull_request:

jobs:
  test:
    name: 🧪 Test with Gradle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [ 'unit', 'e2e' ]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1

      - name: Cache Gradle dependencies
        uses: actions/cache@v4.0.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Docker Compose (for E2E tests)
        if: matrix.test-type == 'e2e'
        run: docker-compose -f docker-compose.e2e.yml up -d

      - name: Set CI environment variable
        run: echo "E2E=${{ matrix.test-type == 'e2e' }}" >> $GITHUB_ENV

      - name: Run Gradle test
        uses: eskatos/gradle-command-action@v3.1.0
        with:
          arguments: test --info ${{ matrix.test-type == 'e2e' && '-Pheadless=true' || '' }}

      - name: Teardown E2E test environment
        if: matrix.test-type == 'e2e'
        run: docker-compose -f docker-compose.e2e.yml down

      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2.15.1
        with:
          files: build/test-results/test/**/*.xml
          check_name: ${{ format('Test Results ({0})', matrix.test-type) }}

      - uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: ${{ format('Test reports ({0})', matrix.test-type) }}
          path: build/reports/tests

  build-docker:
    name: 🔨 Build with Docker Compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build with Docker Compose
        run: docker-compose -f docker-compose.yml build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from type=local,src=/tmp/.buildx-cache

  auto-merge-dependabot:
    name: 🤖 Auto merge dependabot PR
    needs: [ test, build-docker ]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🤖Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: rebase
