name: Build & Test

on:
  push:
  pull_request:

jobs:
  test:
    name: 🧪 Test with Gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set CI environment variable
        run: echo "CI=true" >> $GITHUB_ENV
      - name: Run Gradle test
        uses: eskatos/gradle-command-action@v3.1.0
        with:
          arguments: test --info
      - name: Publish Unit Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2.15.1
        with:
          files: build/test-results/test/**/*.xml
      - uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: Test reports
          path: build/reports/tests

  e2e-tests:
    name: 🧪 E2E Tests with Gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
      - name: Build with Docker Compose
        run: docker-compose -f docker-compose.e2e.yml up -d
      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run Gradle test
        uses: eskatos/gradle-command-action@v3.1.0
        with:
          arguments: --info -Pheadless=true e2eTest

  build-docker:
    name: 🔨 Build with Docker Compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0
      - name: Build with Docker Compose
        run: docker-compose -f docker-compose.yml build

  auto-merge-dependabot:
    name: 🤖  Auto merge dependabot PR
    needs: [ test, e2e-tests, build-docker ]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🤖Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: rebase
