name: Java CI

on:
  push:
  pull_request:

jobs:
  test:
    name: 🧪 Test with Maven
    runs-on: ubuntu-latest
    container: maven:3.9-eclipse-temurin-21-alpine
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
      - run: mvn --quiet test

  build-docker:
    name: 🔨 Build Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build with Docker Compose
        run: docker-compose build

  auto-merge-dependabot:
    name: 🤖  Auto merge dependabot PR
    needs: [ test ]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🤖Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: rebase
